[package]
name = "cargo-catt"
version = "0.1.0"
authors = ["nathan <nathan+dev@electriccoin.co>"]
edition = "2018"
description = "Cargo Check All The Things - comprehensive out-of-the-box safety & hygiene checks."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
